### ISSUE TITLE
Status not updating

### ISSUE THREAD

**Issue by sicelo** [agamez/yappari#36] opened 2015-04-14 22:47 UTC
Whatsapp status does not get updated both on Yappari and on "remote" end. Whether you type your own, or choose from the default ones the behaviour is the same.

**Comment by agamez** [comment] 2015-04-16 09:01
I can't reproduce this...

I've set my status as 'At school' on scratchbox and this status has appeared on my real phone.

This in fact used to happen, but I solved it on 93f770814e32452a8d9213d70f312b54dd756b7a

**Comment by sicelo** [comment] 2015-04-16 10:58
What I notice is that somewhere it does update, but my friends definitely don't see it. Curious log here .. see
(I start by 'checking' what my current status is, then, I set it, It seems somehow gets sent to unknown contact "s.us". Then I check it again, which seems up-to-date, but my contacts have not seen any change):

logMessage():  
UPDATING receipts
logMessage():  
OUTGOING:
<ack>
   class=receipt
   id=1429181315-94
   to=ME@s.whatsapp.net
   type=read

OUTGOING:
<iq>
   id=getstatus_5
   to=s.whatsapp.net
   type=get
   xmlns=status
<status>
<user>
   jid=ME@s.whatsapp.net

INCOMING:
<iq>
   from=s.whatsapp.net
   id=getstatus_5
   type=result
<status>
<user>
   jid=ME@s.whatsapp.net
   t=1429181096
   At school

......
<<other chat here>>
......

Starting sending notification
New notification created with id 134
Finished sending notifications in 243 milliseconds.
logMessage():  
Autoscrolling
Bottom reached
Message ID 1429181393-98
OUTGOING:
<message>
   id=1429181393-98
   to=s.us
   type=text
<body>
   At school...

No chat for s.us found.
Initializing logger for s.us
Logger for s.us initialized successfully.  LastId: 1
logMessage():  
UPDATING receipts
logMessage():  
INCOMING:
<ack>
   class=message
   from=s.us
   id=1429181393-98
   t=1429181394

No chat for s.us found.
Initializing logger for s.us
Logger for s.us initialized successfully.  LastId: 1
logMessage():  
UPDATING receipts
logMessage():  
INCOMING:
<receipt>
   from=s.us
   id=1429181393-98
   t=1429181394

OUTGOING:
<ack>
   class=receipt
   id=1429181393-98
   type=delivered

No chat for s.us found.
Initializing logger for s.us
Logger for s.us initialized successfully.  LastId: 1
logMessage():  
UPDATING receipts
logMessage():  
OUTGOING:
<ack>
   class=receipt
   id=1429181393-98
   type=delivery

OUTGOING:
<iq>
   id=getstatus_6
   to=s.whatsapp.net
   type=get
   xmlns=status
<status>
<user>
   jid=ME@s.whatsapp.net

INCOMING:
<iq>
   from=s.whatsapp.net
   id=getstatus_6
   type=result
<status>
<user>
   jid=ME@s.whatsapp.net
   t=1429181394
   At school...

Updating contact ME@s.whatsapp.net

**Comment by agamez** [comment] 2015-06-14 13:32
Although latest fix is not perfect I'm going to close it for now... it's the best I can do right now.

**Closed as completed by agamez** 2015-06-14 13:32 UTC
